# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 20:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('name', models.CharField(max_length=256)),
                ('floor', models.CharField(max_length=16)),
                ('_open', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuseumObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('title', models.CharField(max_length=256)),
                ('artists', models.ManyToManyField(to='pma.Artist')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pma.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
